### ISSUE TITLE
Add calculated fields to CLASS Assessment

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#39]
- [x] Eric will make changes to fields on CLASS Assessment bundle
  - Each CLASS Assessment will represent one day of one or many "cycles" (sets of scores)
  - There will be up to four cycles, which consist of the 10 dimensions
  - Eric will add these fields and number them by the cycle they correspond to
- [x] Ben will write fields that calculate data based on the values of those cycle scores
  - Average score for each dimension that has a value (all 10 of them) (2 decimal points numeric value)
  - Emotional support score: `( Average PC + (8-NC) + TS + RSP ) / 4`
  - Classroom organization: `( BM + P + ILF ) / 3`
  - Instructional support: `( CD + QF + LM ) / 3`

NB: All acronyms are averages (mean)

**Comment by anderoy** [comment]
I have added the fields as required. I will wait to delete the old fields from the entity until the new calculated fields are added (since removing them will break a views chart that I will need to recreate with the new fields).

**Comment by bnchdrff** [comment]
committed all yr changes @anderoy ! fields in progress :100: .

**Comment by anderoy** [comment]
The fields as built don't meet the specs we discussed. The three "Domain Averages" need to be able to account for and remove the empty fields from the calculation in the case that only 1, 2, or 3 cycles are completed for that coach.

When you said you would be doing this in code, I thought you meant writing some php logic instead of a simple math function that doesn't account for the above conditions.

Also, the Dimension averages are missing. Coaches will need to be able to see these average scores along with the 3 Domain average scores.

**Comment by gl2748** [comment]
Thanks Eric, I am on this now.

**Comment by anderoy** [comment]
Also, make sure that the three Domain averages are in fact calculating averages. It looks like the Instructional Support Average (the last one) isn't dividing the total.

**Comment by anderoy** [comment]
@bnchdrff and @gl2748 what is the status of this?

**Comment by gl2748** [comment]
@anderoy, all the calculations are done in php but there is something stopping $form_state['values'] from being set. Not sure how long it will take to figure it out. Working on fix today. In the meantime the math fields can be setup to cover the scenario where every cycle is completed as a stop gap. Let me know if you want me to implement that.

**Comment by gl2748** [comment]
It looks like the issue is with the Ajax call on the dropdownwidget  to select the score on each cycle field. On a form form_state['values'] is only loaded after an ajax has been fired somewhere on the form...

**Comment by anderoy** [comment]
So long as the 10 Dimension average fields and the 3 domain average field are in place with field names set in stone and available for me to plug-in to views, and the math error is fixed, I can accept a stop-gap solution if it allows me to finish the final tweaks I need to make and we can get all changes committed to code and pushed to live early today.

My supervisor is unhappy and the coaches are asking me when this will be ready.

**Comment by bnchdrff** [comment]
As an interim fix I think we should have the coaches use the site without
average functionality and then retroactively add the values later.

**Comment by gl2748** [comment]
Ok that make sense, I will be working on the averages in the mean time.

**Comment by anderoy** [comment]
The issue with accepting an interim fix is that one of the "carrots" to get some of the less active coaches to use the system is that fact that it will ease their reporting and save them the time of calculating everything themselves.

But if I have to accept the interim fix, please just make sure that the domains are calculating correctly. I think I could fix it, but since you said that you would take care of the calculations I will let you do it. For the last two math expressions, you are missing the "f" to start the function after first declaring the function.

All other changes for the moment have been made by me. You can wrap up the interim fix, commit to code and push to live.

**Comment by bnchdrff** [comment]
fixed in https://github.com/ESDet/esdportal_e3/commit/65095df1a557440f7e1aa71b1c8d94af8e81edaa -- please review at dev site https://29-e3teachers-3mhev6qb5ihtc.us.platform.sh/ & we can then push to live!

**Comment by anderoy** [comment]
From what I see, the calculated fields are still not working. Coming back with values in the double digits which is a huge red flag.

I guess that there is still no solution for calculating values from a single cycle?

So the desired solution seems far away and the stop-gap solution is still not working properly.

**Comment by anderoy** [comment]
I am struggling to see why this is so complicated. Here is what I think:

The following little bit of php (or something like it, I haven't used php in over a year) should be used to calculate the average score for each domain:
```php
var denom = 0;
var allpc = [field_pc_cycle_1, field_pc_cycle_2, field_pc_cycle_3, field_pc_cycle_4];
foreach (allpc) {
	if (allpc > 0) {
		denom++;
		}
	}
return field_pc_cycle_1 + field_pc_cycle_2 + field_pc_cycle_3 + field_pc_cycle_4 / denom
```

Then just use those results in the final three domain calculations.

Is there any reason this wouldn't work?

**Comment by gl2748** [comment]
Eric do you have an example of incorrect value that you are getting on the test site? I have this running locally and everything is working...

**Comment by bnchdrff** [comment]
i think eric is seeing the old mathfields that are still present on the dev
site -- we need to remove those

**Comment by bnchdrff** [comment]
@gl2748 let's do a hook_update to remove those fields, if necessary, and then do a test deployment using data from the live portal... i'll give u a dump!

**Comment by anderoy** [comment]
Thanks guys. How was my beginner php?

**Comment by bnchdrff** [comment]
very javascript-y!

**Comment by bnchdrff** [comment]
recommended reading https://en.wikipedia.org/wiki/Operator_associativity :)

**Comment by anderoy** [comment]
Yeah, so i missed a few parentheses...I tried.
